# Generated by Django 4.2.11 on 2026-04-14 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0002_workloadallocation_audit_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workloadallocation',
            options={'ordering': ['academic_year', 'academic']},
        ),
        migrations.AlterField(
            model_name='workloadallocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workloadallocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
