# Generated by Django 4.2.11 on 2026-04-18 20:26

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('allocations', '0004_teachingallocationitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('expected_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_roles', to='departments.department')),
            ],
            options={
                'db_table': 'allocations_researchrole',
                'ordering': ['name'],
                'unique_together': {('department', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('expected_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_roles', to='departments.department')),
            ],
            options={
                'db_table': 'allocations_adminrole',
                'ordering': ['name'],
                'unique_together': {('department', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ResearchAllocationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=5)),
                ('calculated_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('research_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_items', to='allocations.researchrole')),
                ('workload_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_items', to='allocations.workloadallocation')),
            ],
            options={
                'db_table': 'allocations_researchallocationitem',
                'ordering': ['research_role__name'],
                'unique_together': {('workload_allocation', 'research_role')},
            },
        ),
        migrations.CreateModel(
            name='AdminAllocationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=5)),
                ('calculated_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('admin_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_items', to='allocations.adminrole')),
                ('workload_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_items', to='allocations.workloadallocation')),
            ],
            options={
                'db_table': 'allocations_adminallocationitem',
                'ordering': ['admin_role__name'],
                'unique_together': {('workload_allocation', 'admin_role')},
            },
        ),
    ]
