# Generated by Django 4.2.11 on 2026-04-19 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academic',
            name='email',
        ),
    ]
