# Generated by Django 4.2.11 on 2026-04-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_academic_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
