# Generated by Django 4.2.11 on 2026-04-16 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('years', '0001_initial'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleTeachingAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('academic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_teaching_allocations', to='academics.academic')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_teaching_allocations', to='years.academicyear')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_allocations', to='modules.module')),
            ],
            options={
                'db_table': 'modules_module_teaching_allocation',
                'unique_together': {('module', 'academic', 'academic_year')},
            },
        ),
    ]
