# Generated by Django 4.2.11 on 2026-04-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_moduleteachingallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleteachingallocation',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
    ]
