# Generated by Django 4.2.11 on 2026-04-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_alter_moduleteachingallocation_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='credit_hours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
